### ISSUE TITLE
フッターのコピーライトと問い合わせ先を変更してほしい

### ISSUE THREAD

**Issue by htomine** [adwd/qiita-to#1]
@adwd はじめまして、Incrementsのほうからきました。
Qiitaへの投稿ありがとうございます！qiita-to も楽しく拝見いたしました ;)
閲覧された方が混乱するとよくないので、フッターのコピーライトがIncrementsのままな点と、問い合わせ先も弊社のZendeskになってしまっているので、それらの点を修正いただけますか？
よろしくお願いします 🙏 

https://github.com/adwd/qiita-to/blob/df7c624aa664740c78e56122d3d25e3891f7b6b7/components/Footer.vue#L30

**Comment by adwd** [comment]
@htomine すいません、そこまずかったですね。ごめんなさい。該当箇所(コピーライトが入っていることろと問い合わせ先)を削除する形で大丈夫ですか？

**Comment by htomine** [comment]
@adwd はい、それで大丈夫です 👍

**Comment by adwd** [comment]
@htomine 了解です！今日中にやります 🙇 🙇

**Comment by adwd** [comment]
@htomine #2 で修正しました。お手数おかけしました 🙏 
https://qiita-to.herokuapp.com/
